# -*- coding: utf-8 -*-
"""ocr_using_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12We02vS5o4CiaCd81ILFWvFvOUumLW4e
"""

import os
import pytesseract
import os
from PIL import Image

pytesseract.pytesseract.tesseract_cmd = r"E:\tsss\tesseract.exe"

def convert():
  img = Image.open('img.jpg')
  text = pytesseract.image_to_string(img)
  print(text)

convert()